### ISSUE TITLE
How to manage appendices?

### ISSUE THREAD

**Issue by robitalec** [quarto-ext/manuscript-template-rstudio#6]
In the quarto books format, we see there is an appendices option:

```
book:
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - tools.qmd
    - resources.qmd
```

https://quarto.org/docs/books/book-structure.html#parts-appendices

Is there some similar option for manuscripts? Appendices or supplemental materials are common with manuscripts and within the main body of text doesn't quite feel right. At the moment, my solution is to just use [{{< include >}}](https://quarto.org/docs/authoring/includes.html) in the main body, with unnumbered headers after the references. I also considered using the notebooks section, but it isn't really compatible with appendices because it seems to expose all code chunks.
